use std::fs;

#[test]
fn expand_target_directory_filters_to_aivi_sources() {
    let dir = tempfile::tempdir().expect("tempdir");
    let aivi_path = dir.path().join("main.aivi");
    let cargo_lock_path = dir.path().join("Cargo.lock");
    let text_path = dir.path().join("notes.txt");

    fs::write(&aivi_path, "module Main\n").expect("write main.aivi");
    fs::write(
        &cargo_lock_path,
        "# This file is automatically @generated by Cargo.\n",
    )
    .expect("write Cargo.lock");
    fs::write(&text_path, "not aivi\n").expect("write notes.txt");

    let resolved =
        aivi::resolve_target(dir.path().to_str().expect("utf8 path")).expect("resolve target");

    assert_eq!(resolved, vec![aivi_path]);
}
